// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::{collections::HashMap, sync::Arc};

use iota_json_rpc_types::{BalanceChange, IotaObjectData, IotaObjectDataOptions, ObjectChange};
use iota_types::{
    base_types::{IotaAddress, ObjectID, ObjectRef, SequenceNumber},
    effects::{ObjectRemoveKind, TransactionEffectsAPI},
    error::IotaObjectResponseError,
    object::{Object, Owner},
    quorum_driver_types::ExecuteTransactionRequestV1,
    storage::WriteKind,
    transaction::{Transaction, TransactionDataAPI},
    transaction_executor::TransactionExecutor,
};
use move_core_types::language_storage::TypeTag;
use tonic::{Request, Response, Status};
use tracing::{debug, warn};

use crate::{
    conversions,
    node::{
        ExecuteTransactionRequest, ExecuteTransactionResponse, GetObjectRequest, GetObjectResponse,
        TransactionResponseOptions, node_service_server::NodeService,
    },
    types::GrpcReader,
};

/// Node gRPC Service - handles core blockchain operations (objects,
/// transactions, balances, etc.)
pub struct NodeGrpcService {
    pub grpc_reader: Arc<GrpcReader>,
    pub transaction_executor: Option<Arc<dyn TransactionExecutor>>,
}

impl NodeGrpcService {
    /// Create a new NodeGrpcService with concrete types
    pub fn new(
        grpc_reader: Arc<GrpcReader>,
        transaction_executor: Option<Arc<dyn TransactionExecutor>>,
    ) -> Self {
        Self {
            grpc_reader,
            transaction_executor,
        }
    }
}

// The `NodeService` is the auto-generated trait from the protobuf definition.
// It's generated by tonic/protobuf and defines the interface that any gRPC node
// service must implement.
#[tonic::async_trait]
impl NodeService for NodeGrpcService {
    async fn execute_transaction(
        &self,
        request: Request<ExecuteTransactionRequest>,
    ) -> Result<Response<ExecuteTransactionResponse>, Status> {
        let req = request.into_inner();
        debug!("execute_transaction called");

        // Deserialize transaction data directly from bytes
        let tx_data: Transaction = bcs::from_bytes(&req.tx_bytes).map_err(|e| {
            Status::invalid_argument(format!("Failed to deserialize transaction data: {e}"))
        })?;

        // Determine what data to include from options
        let options = req.options.as_ref();
        let show_events = is_option_enabled(options, |o| o.show_events);
        let show_effects = is_option_enabled(options, |o| o.show_effects);
        let show_object_changes = is_option_enabled(options, |o| o.show_object_changes);
        let show_balance_changes = is_option_enabled(options, |o| o.show_balance_changes);

        // Extract sender address before moving tx_data
        let sender_address = tx_data.data().intent_message().value.sender();

        // Create ExecuteTransactionRequestV1 (IOTA native type)
        let execute_request = ExecuteTransactionRequestV1 {
            transaction: tx_data,
            include_events: show_events,
            include_input_objects: show_balance_changes || show_object_changes,
            include_output_objects: show_balance_changes || show_object_changes || show_effects,
            include_auxiliary_data: false,
        };

        // Call TransactionExecutor directly
        let executor = self
            .transaction_executor
            .as_ref()
            .ok_or_else(|| Status::unimplemented("Transaction execution not available"))?;

        let response = executor
            .execute_transaction(execute_request, None)
            .await
            .map_err(|e| Status::internal(format!("Transaction execution failed: {e}")))?;

        // Convert IOTA native response to gRPC protobuf
        let digest = *response.effects.effects.transaction_digest();
        // Note: TransactionEffects doesn't have timestamp_ms, we'll use current time as
        // placeholder
        let timestamp_ms = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        // Convert optional fields based on request options
        let transaction = if is_option_enabled(options, |o| o.show_input) {
            Some(serialize_to_bcs(&response.effects.effects, "Transaction")?)
        } else {
            None
        };

        let raw_transaction = if is_option_enabled(options, |o| o.show_raw_input) {
            Some(req.tx_bytes)
        } else {
            None
        };

        let effects = if is_option_enabled(options, |o| o.show_effects) {
            Some(serialize_to_bcs(&response.effects.effects, "Effects")?)
        } else {
            None
        };

        let raw_effects =
            if is_option_enabled(options, |o| o.show_raw_effects) {
                Some(bcs::to_bytes(&response.effects.effects).map_err(|e| {
                    Status::internal(format!("Raw effects serialization failed: {e}"))
                })?)
            } else {
                None
            };

        let events = if show_events {
            // Events are available in the response.events field, not
            // response.effects.events
            if let Some(ref tx_events) = response.events {
                serialize_collection_to_bcs(tx_events.data.iter(), "Event")?
            } else {
                vec![]
            }
        } else {
            vec![]
        };

        let object_changes = if show_object_changes {
            match (&response.input_objects, &response.output_objects) {
                (Some(input_objects), Some(output_objects)) => {
                    let changes = compute_object_changes(
                        sender_address,
                        response.effects.effects.modified_at_versions(),
                        response.effects.effects.all_changed_objects(),
                        response.effects.effects.all_removed_objects(),
                        input_objects,
                        output_objects,
                    );
                    serialize_collection_to_bcs(changes.into_iter(), "Object change")?
                }
                _ => {
                    warn!("Cannot compute object changes: missing input or output objects");
                    vec![]
                }
            }
        } else {
            vec![]
        };

        let balance_changes = if show_balance_changes {
            match (&response.input_objects, &response.output_objects) {
                (Some(input_objects), Some(output_objects)) => {
                    let changes = derive_balance_changes(input_objects, output_objects);
                    serialize_collection_to_bcs(changes.into_iter(), "Balance change")?
                }
                _ => vec![],
            }
        } else {
            vec![]
        };

        debug!("Transaction executed successfully via direct TransactionExecutor");

        Ok(Response::new(ExecuteTransactionResponse {
            digest: Some(crate::common::Digest {
                digest: digest.into_inner().to_vec(),
            }),
            transaction,
            raw_transaction,
            effects,
            events,
            object_changes,
            balance_changes,
            timestamp_ms: Some(timestamp_ms),
            confirmed_local_execution: Some(true),
            checkpoint: None, // Not available yet
            errors: vec![],
            raw_effects,
        }))
    }

    async fn get_object(
        &self,
        request: Request<GetObjectRequest>,
    ) -> Result<Response<GetObjectResponse>, Status> {
        let req = request.into_inner();
        debug!("get_object called");

        // Extract object ID from gRPC request
        let object_id_bytes = req
            .object_id
            .as_ref()
            .ok_or_else(|| Status::invalid_argument("Object ID is required"))?;

        if object_id_bytes.address.len() != 32 {
            return Err(Status::invalid_argument(format!(
                "Object ID must be 32 bytes, got {}",
                object_id_bytes.address.len()
            )));
        }

        let mut bytes = [0u8; 32];
        bytes.copy_from_slice(&object_id_bytes.address);
        let object_id = ObjectID::from_bytes(bytes)
            .map_err(|e| Status::invalid_argument(format!("Invalid object ID: {e}")))?;

        // Convert gRPC options to JSON-RPC options
        let options = req.options.map(|opts| IotaObjectDataOptions {
            show_type: opts.show_type,
            show_owner: opts.show_owner,
            show_previous_transaction: opts.show_previous_transaction,
            show_display: opts.show_display,
            show_content: opts.show_content,
            show_bcs: opts.show_bcs,
            show_storage_rebate: opts.show_storage_rebate,
        });

        // Call GrpcReader directly to get the object
        let object_result = self.grpc_reader.get_object(&object_id);

        // Handle errors by converting them to proper gRPC ObjectError
        let grpc_response = match object_result {
            Ok(Some(object)) => {
                // Object found - create successful response
                create_object_data_response(object, options)?
            }
            Ok(None) => {
                // Object not found - create NotExists error
                let not_exists_error = IotaObjectResponseError::NotExists { object_id };
                GetObjectResponse {
                    data: None,
                    error: Some(conversions::iota_object_response_error_to_grpc(
                        not_exists_error,
                    )),
                }
            }
            Err(e) => {
                // Convert storage/access errors to appropriate ObjectError
                match e.downcast_ref::<iota_types::error::IotaError>() {
                    Some(iota_error) => GetObjectResponse {
                        data: None,
                        error: Some(conversions::iota_error_to_grpc(iota_error.clone())),
                    },
                    None => {
                        // For non-IotaError types, create an Unknown error
                        return Err(Status::internal(format!(
                            "Failed to get object from GrpcReader: {e}"
                        )));
                    }
                }
            }
        };

        debug!("Object retrieved successfully");
        Ok(Response::new(grpc_response))
    }
}

/// Helper function to create object data response
fn create_object_data_response(
    object: Object,
    options: Option<IotaObjectDataOptions>,
) -> Result<GetObjectResponse, Status> {
    let object_ref = object.compute_object_reference();
    let data = IotaObjectData::new(
        object_ref,
        object,
        None, // layout - not needed for basic object data
        options.clone().unwrap_or_default(),
        None, // display_fields - not computed here
    )
    .map_err(|e| Status::internal(format!("Failed to create IotaObjectData: {e}")))?;

    // Convert optional fields based on request options
    let opts = options.as_ref();

    let display = if opts.map(|o| o.show_display).unwrap_or(false) && data.display.is_some() {
        Some(serialize_to_bcs(&data.display, "Display")?)
    } else {
        None
    };

    let content = if opts.map(|o| o.show_content).unwrap_or(false) && data.content.is_some() {
        Some(serialize_to_bcs(&data.content, "Content")?)
    } else {
        None
    };

    let bcs = if opts.map(|o| o.show_bcs).unwrap_or(false) && data.bcs.is_some() {
        Some(serialize_to_bcs(&data.bcs, "BCS data")?)
    } else {
        None
    };

    Ok(GetObjectResponse {
        data: Some(crate::node::ObjectData {
            object_id: Some(crate::common::Address {
                address: data.object_id.into_bytes().to_vec(),
            }),
            version: data.version.value(),
            digest: Some(crate::common::Digest {
                digest: data.digest.into_inner().to_vec(),
            }),
            r#type: if opts.map(|o| o.show_type).unwrap_or(false) {
                data.type_.map(|t| t.to_string())
            } else {
                None
            },
            owner: if opts.map(|o| o.show_owner).unwrap_or(false) {
                data.owner.map(|o| o.to_string())
            } else {
                None
            },
            previous_transaction: if opts.map(|o| o.show_previous_transaction).unwrap_or(false) {
                data.previous_transaction.map(|tx| crate::common::Digest {
                    digest: tx.into_inner().to_vec(),
                })
            } else {
                None
            },
            storage_rebate: if opts.map(|o| o.show_storage_rebate).unwrap_or(false) {
                data.storage_rebate
            } else {
                None
            },
            display,
            content,
            bcs,
        }),
        error: None,
    })
}

/// Helper function to serialize data to BCS and handle errors consistently
fn serialize_to_bcs<T: serde::Serialize>(
    data: &T,
    context: &str,
) -> Result<crate::common::BcsData, Status> {
    crate::common::BcsData::serialize_from(data)
        .map_err(|e| Status::internal(format!("{context} BCS serialization failed: {e}")))
}

/// Helper function to convert a collection to BCS serialized Vec
fn serialize_collection_to_bcs<T: serde::Serialize>(
    items: impl Iterator<Item = T>,
    context: &str,
) -> Result<Vec<crate::common::BcsData>, Status> {
    items
        .map(|item| serialize_to_bcs(&item, context))
        .collect::<Result<Vec<_>, _>>()
}

/// Helper function to check if an option is enabled with default false
fn is_option_enabled<F>(options: Option<&TransactionResponseOptions>, getter: F) -> bool
where
    F: FnOnce(&TransactionResponseOptions) -> bool,
{
    options.map(getter).unwrap_or(false)
}

// NOTE: The following implementations (coins, derive_balance_changes,
// compute_object_changes) are custom versions for the gRPC API. We cannot
// directly reuse the JSON-RPC implementations due to circular dependency
// issues:
// - iota-grpc-api would need to depend on iota-json-rpc
// - But iota-json-rpc depends on iota-config
// - And iota-config depends on iota-grpc-api (because NodeConfig contains an
//   `iota_grpc_node::Config` field to configure the gRPC service settings like
//   bind address, buffer sizes, etc. as part of the unified node configuration)
// This creates a circular dependency that prevents us from importing the
// JSON-RPC functions.
//
// These implementations follow similar logic to the JSON-RPC versions but work
// directly with the objects available in the transaction execution response.

/// Extract coins from objects for balance change calculation
fn coins(objects: &[Object]) -> impl Iterator<Item = (&IotaAddress, (TypeTag, u64))> + '_ {
    objects.iter().filter_map(|object| {
        let address = match object.owner() {
            Owner::AddressOwner(address) => address,
            Owner::ObjectOwner(address) => address,
            Owner::Shared { .. } | Owner::Immutable => return None,
        };

        // Extract coin data if this is a coin object
        if let Some(coin) = object.as_coin_maybe() {
            if let Some(coin_type) = object.coin_type_maybe() {
                return Some((address, (coin_type, coin.value())));
            }
        }
        None
    })
}

/// Derive balance changes directly from input and output objects
/// This follows the same logic as the JSON-RPC version but works with objects
/// directly
fn derive_balance_changes(
    input_objects: &[Object],
    output_objects: &[Object],
) -> Vec<BalanceChange> {
    // 1. subtract all input coins
    let balances = coins(input_objects).fold(
        std::collections::BTreeMap::<_, i128>::new(),
        |mut acc, (address, (coin_type, amount))| {
            *acc.entry((address, coin_type.clone())).or_default() -= amount as i128;
            acc
        },
    );

    // 2. add all output coins
    let balances =
        coins(output_objects).fold(balances, |mut acc, (address, (coin_type, amount))| {
            *acc.entry((address, coin_type.clone())).or_default() += amount as i128;
            acc
        });

    balances
        .into_iter()
        .filter_map(|((address, coin_type), amount)| {
            if amount == 0 {
                return None;
            }

            Some(BalanceChange {
                owner: Owner::AddressOwner(*address),
                coin_type,
                amount,
            })
        })
        .collect()
}

/// Compute object changes directly from available objects
/// This follows the same logic as the JSON-RPC version but works with objects
/// directly
fn compute_object_changes(
    sender: IotaAddress,
    modified_at_versions: Vec<(ObjectID, SequenceNumber)>,
    all_changed_objects: Vec<(ObjectRef, Owner, WriteKind)>,
    all_removed_objects: Vec<(ObjectRef, ObjectRemoveKind)>,
    input_objects: &[Object],
    output_objects: &[Object],
) -> Vec<ObjectChange> {
    let mut object_changes = vec![];
    let modify_at_version = modified_at_versions.into_iter().collect::<HashMap<_, _>>();

    // Create a lookup map for all available objects
    let mut all_objects = HashMap::new();
    for obj in input_objects.iter().chain(output_objects.iter()) {
        all_objects.insert((obj.id(), obj.version()), obj);
    }

    // Process changed objects
    for ((object_id, version, digest), owner, kind) in all_changed_objects {
        if let Some(obj) = all_objects.get(&(object_id, version)) {
            if let Some(type_) = obj.type_() {
                let object_type = type_.clone().into();

                match kind {
                    WriteKind::Mutate => object_changes.push(ObjectChange::Mutated {
                        sender,
                        owner,
                        object_type,
                        object_id,
                        version,
                        previous_version: modify_at_version
                            .get(&object_id)
                            .cloned()
                            .unwrap_or_default(),
                        digest,
                    }),
                    WriteKind::Create => object_changes.push(ObjectChange::Created {
                        sender,
                        owner,
                        object_type,
                        object_id,
                        version,
                        digest,
                    }),
                    _ => {}
                }
            } else if let Some(p) = obj.data.try_as_package() {
                if kind == WriteKind::Create {
                    object_changes.push(ObjectChange::Published {
                        package_id: p.id(),
                        version: p.version(),
                        digest,
                        modules: p.serialized_module_map().keys().cloned().collect(),
                    });
                }
            }
        }
    }

    // Process removed objects
    for ((id, version, _), kind) in all_removed_objects {
        // Look for the object in our available objects (best-effort)
        if let Some(obj) = all_objects.get(&(id, version)) {
            if let Some(type_) = obj.type_() {
                let object_type = type_.clone().into();
                match kind {
                    ObjectRemoveKind::Delete => object_changes.push(ObjectChange::Deleted {
                        sender,
                        object_type,
                        object_id: id,
                        version,
                    }),
                    ObjectRemoveKind::Wrap => object_changes.push(ObjectChange::Wrapped {
                        sender,
                        object_type,
                        object_id: id,
                        version,
                    }),
                }
            }
        }
    }

    object_changes
}
