// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::sync::Arc;

use iota_json_rpc_types::{IotaObjectData, IotaObjectDataOptions};
use iota_types::{base_types::ObjectID, error::IotaObjectResponseError, object::Object};
use tonic::{Request, Response, Status};
use tracing::debug;

use crate::{
    conversions,
    read::{GetObjectRequest, GetObjectResponse, ObjectData, read_service_server::ReadService},
    types::GrpcReader,
};

pub struct ReadGrpcService {
    pub grpc_reader: Arc<GrpcReader>,
}

impl ReadGrpcService {
    pub fn new(grpc_reader: Arc<GrpcReader>) -> Self {
        Self { grpc_reader }
    }
}

// The `ReadService` is the auto-generated trait from the protobuf definition.
// It's generated by tonic/protobuf and defines the interface that any gRPC read
// service must implement.
#[tonic::async_trait]
impl ReadService for ReadGrpcService {
    async fn get_object(
        &self,
        request: Request<GetObjectRequest>,
    ) -> Result<Response<GetObjectResponse>, Status> {
        let req = request.into_inner();
        debug!("get_object called");

        // Extract object ID from gRPC request
        let object_id_bytes = req
            .object_id
            .as_ref()
            .ok_or_else(|| Status::invalid_argument("Object ID is required"))?;

        if object_id_bytes.address.len() != 32 {
            return Err(Status::invalid_argument(format!(
                "Object ID must be 32 bytes, got {}",
                object_id_bytes.address.len()
            )));
        }

        let mut bytes = [0u8; 32];
        bytes.copy_from_slice(&object_id_bytes.address);
        let object_id = ObjectID::from_bytes(bytes)
            .map_err(|e| Status::invalid_argument(format!("Invalid object ID: {e}")))?;

        // Convert gRPC options to JSON-RPC options
        let options = req.options.map(|opts| IotaObjectDataOptions {
            show_type: opts.show_type,
            show_owner: opts.show_owner,
            show_previous_transaction: opts.show_previous_transaction,
            show_display: opts.show_display,
            show_content: opts.show_content,
            show_bcs: opts.show_bcs,
            show_storage_rebate: opts.show_storage_rebate,
        });

        // Call GrpcReader directly to get the object
        let object_result = self.grpc_reader.get_object(&object_id);

        // Handle errors by converting them to proper gRPC ObjectError
        let grpc_response = match object_result {
            Ok(Some(object)) => {
                // Object found - create successful response
                create_object_data_response(object, options)?
            }
            Ok(None) => {
                // Object not found - create NotExists error
                let not_exists_error = IotaObjectResponseError::NotExists { object_id };
                GetObjectResponse {
                    data: None,
                    error: Some(conversions::iota_object_response_error_to_grpc(
                        not_exists_error,
                    )),
                }
            }
            Err(e) => {
                // Convert storage/access errors to appropriate ObjectError
                match e.downcast_ref::<iota_types::error::IotaError>() {
                    Some(iota_error) => GetObjectResponse {
                        data: None,
                        error: Some(conversions::iota_error_to_grpc(iota_error.clone())),
                    },
                    None => {
                        // For non-IotaError types, create an Unknown error
                        return Err(Status::internal(format!(
                            "Failed to get object from GrpcReader: {e}"
                        )));
                    }
                }
            }
        };

        debug!("Object retrieved successfully");
        Ok(Response::new(grpc_response))
    }
}

/// Helper function to create object data response
fn create_object_data_response(
    object: Object,
    options: Option<IotaObjectDataOptions>,
) -> Result<GetObjectResponse, Status> {
    let object_ref = object.compute_object_reference();
    let data = IotaObjectData::new(
        object_ref,
        object,
        None, // layout - not needed for basic object data
        options.clone().unwrap_or_default(),
        None, // display_fields - not computed here
    )
    .map_err(|e| Status::internal(format!("Failed to create IotaObjectData: {e}")))?;

    // Convert optional fields based on request options
    let opts = options.as_ref();

    let display = if opts.map(|o| o.show_display).unwrap_or(false) && data.display.is_some() {
        Some(serialize_to_bcs(&data.display, "Display")?)
    } else {
        None
    };

    let content = if opts.map(|o| o.show_content).unwrap_or(false) && data.content.is_some() {
        Some(serialize_to_bcs(&data.content, "Content")?)
    } else {
        None
    };

    let bcs = if opts.map(|o| o.show_bcs).unwrap_or(false) && data.bcs.is_some() {
        Some(serialize_to_bcs(&data.bcs, "BCS data")?)
    } else {
        None
    };

    Ok(GetObjectResponse {
        data: Some(ObjectData {
            object_id: Some(crate::common::Address {
                address: data.object_id.into_bytes().to_vec(),
            }),
            version: data.version.value(),
            digest: Some(crate::common::Digest {
                digest: data.digest.into_inner().to_vec(),
            }),
            object_type: if opts.map(|o| o.show_type).unwrap_or(false) {
                data.type_.map(|t| t.to_string())
            } else {
                None
            },
            owner: if opts.map(|o| o.show_owner).unwrap_or(false) {
                data.owner.map(|o| o.to_string())
            } else {
                None
            },
            previous_transaction: if opts.map(|o| o.show_previous_transaction).unwrap_or(false) {
                data.previous_transaction.map(|tx| crate::common::Digest {
                    digest: tx.into_inner().to_vec(),
                })
            } else {
                None
            },
            storage_rebate: if opts.map(|o| o.show_storage_rebate).unwrap_or(false) {
                data.storage_rebate
            } else {
                None
            },
            display,
            content,
            bcs,
        }),
        error: None,
    })
}

/// Helper function to serialize data to BCS and handle errors consistently
fn serialize_to_bcs<T: serde::Serialize>(
    data: &T,
    context: &str,
) -> Result<crate::common::BcsData, Status> {
    crate::common::BcsData::serialize_from(data)
        .map_err(|e| Status::internal(format!("{context} BCS serialization failed: {e}")))
}
