// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::sync::Arc;

use iota_json_rpc_types::{
    DisplayFieldsResponse, EventFilter, IotaObjectData, IotaObjectDataOptions,
};
use iota_types::{
    base_types::ObjectID,
    display::DisplayVersionUpdatedEvent,
    error::IotaObjectResponseError,
    object::{Object, ObjectRead},
};
use move_core_types::annotated_value::MoveStructLayout;
use tonic::{Request, Response, Status};
use tracing::debug;

use crate::{
    conversions,
    read::{GetObjectRequest, GetObjectResponse, ObjectData, read_service_server::ReadService},
    types::GrpcReader,
};

pub struct ReadGrpcService {
    pub grpc_reader: Arc<GrpcReader>,
}

impl ReadGrpcService {
    pub fn new(grpc_reader: Arc<GrpcReader>) -> Self {
        Self { grpc_reader }
    }
}

// The `ReadService` is the auto-generated trait from the protobuf definition.
// It's generated by tonic/protobuf and defines the interface that any gRPC read
// service must implement.
#[tonic::async_trait]
impl ReadService for ReadGrpcService {
    async fn get_object(
        &self,
        request: Request<GetObjectRequest>,
    ) -> Result<Response<GetObjectResponse>, Status> {
        let req = request.into_inner();
        debug!("get_object called");

        // Extract object ID from gRPC request
        let object_id_bytes = req
            .object_id
            .as_ref()
            .ok_or_else(|| Status::invalid_argument("Object ID is required"))?;

        if object_id_bytes.address.len() != 32 {
            return Err(Status::invalid_argument(format!(
                "Object ID must be 32 bytes, got {}",
                object_id_bytes.address.len()
            )));
        }

        let mut bytes = [0u8; 32];
        bytes.copy_from_slice(&object_id_bytes.address);
        let object_id = ObjectID::from_bytes(bytes)
            .map_err(|e| Status::invalid_argument(format!("Invalid object ID: {e}")))?;

        // Convert gRPC options to JSON-RPC options
        let options = req.options.map(|opts| IotaObjectDataOptions {
            show_type: opts.show_type,
            show_owner: opts.show_owner,
            show_previous_transaction: opts.show_previous_transaction,
            show_display: opts.show_display,
            show_content: opts.show_content,
            show_bcs: opts.show_bcs,
            show_storage_rebate: opts.show_storage_rebate,
        });

        let object_read_result = self.grpc_reader.get_object_read(&object_id);

        // Handle ObjectRead
        let grpc_response = match object_read_result {
            Ok(object_read) => {
                match object_read {
                    ObjectRead::NotExists(id) => {
                        // Object not found - create NotExists error
                        let not_exists_error = IotaObjectResponseError::NotExists { object_id: id };
                        GetObjectResponse {
                            data: None,
                            error: Some(conversions::iota_object_response_error_to_grpc(
                                not_exists_error,
                            )),
                        }
                    }
                    ObjectRead::Deleted(object_ref) => {
                        // Object was deleted - create Deleted error
                        let deleted_error = IotaObjectResponseError::Deleted {
                            object_id: object_ref.0,
                            version: object_ref.1,
                            digest: object_ref.2,
                        };
                        GetObjectResponse {
                            data: None,
                            error: Some(conversions::iota_object_response_error_to_grpc(
                                deleted_error,
                            )),
                        }
                    }
                    ObjectRead::Exists(object_ref, object, layout) => {
                        // Object exists - create successful response with layout
                        create_object_data_response_with_layout(
                            &self.grpc_reader,
                            object_ref,
                            object,
                            layout,
                            options,
                        )
                        .await?
                    }
                }
            }
            Err(e) => {
                // Convert storage/access errors to appropriate ObjectError
                match e.downcast_ref::<iota_types::error::IotaError>() {
                    Some(iota_error) => GetObjectResponse {
                        data: None,
                        error: Some(conversions::iota_error_to_grpc(iota_error.clone())),
                    },
                    None => {
                        // For non-IotaError types, create an Unknown error
                        return Err(Status::internal(format!(
                            "Failed to get object from GrpcReader: {e}"
                        )));
                    }
                }
            }
        };

        debug!("Object retrieved successfully");
        Ok(Response::new(grpc_response))
    }
}

/// Helper function to create object data response with layout information
async fn create_object_data_response_with_layout(
    grpc_reader: &Arc<crate::types::GrpcReader>,
    object_ref: iota_types::base_types::ObjectRef,
    object: Object,
    layout: Option<MoveStructLayout>,
    options: Option<IotaObjectDataOptions>,
) -> Result<GetObjectResponse, Status> {
    // Create IotaObjectData with layout information
    let display_fields = if options.as_ref().map(|o| o.show_display).unwrap_or(false) {
        // Use full display fields computation
        match get_display_fields(grpc_reader, &object, &layout).await {
            Ok(rendered_fields) => Some(rendered_fields),
            Err(e) => {
                // Log the error but don't fail the request - graceful fallback
                debug!("Failed to compute display fields: {e}");
                None
            }
        }
    } else {
        None
    };

    let data = IotaObjectData::new(
        object_ref,
        object,
        layout, // Use the layout from ObjectRead
        options.clone().unwrap_or_default(),
        display_fields, // Display fields computation
    )
    .map_err(|e| Status::internal(format!("Failed to create IotaObjectData: {e}")))?;

    // Convert optional fields based on request options
    let opts = options.as_ref();

    let display = if opts.map(|o| o.show_display).unwrap_or(false) && data.display.is_some() {
        Some(serialize_to_bcs(&data.display, "Display")?)
    } else {
        None
    };

    let content = if opts.map(|o| o.show_content).unwrap_or(false) && data.content.is_some() {
        Some(serialize_to_bcs(&data.content, "Content")?)
    } else {
        None
    };

    let bcs = if opts.map(|o| o.show_bcs).unwrap_or(false) && data.bcs.is_some() {
        Some(serialize_to_bcs(&data.bcs, "BCS data")?)
    } else {
        None
    };

    Ok(GetObjectResponse {
        data: Some(ObjectData {
            object_id: Some(crate::common::Address {
                address: data.object_id.into_bytes().to_vec(),
            }),
            version: data.version.value(),
            digest: Some(crate::common::Digest {
                digest: data.digest.into_inner().to_vec(),
            }),
            object_type: if opts.map(|o| o.show_type).unwrap_or(false) {
                data.type_.map(|t| t.to_string())
            } else {
                None
            },
            owner: if opts.map(|o| o.show_owner).unwrap_or(false) {
                data.owner.map(|o| o.to_string())
            } else {
                None
            },
            previous_transaction: if opts.map(|o| o.show_previous_transaction).unwrap_or(false) {
                data.previous_transaction.map(|tx| crate::common::Digest {
                    digest: tx.into_inner().to_vec(),
                })
            } else {
                None
            },
            storage_rebate: if opts.map(|o| o.show_storage_rebate).unwrap_or(false) {
                data.storage_rebate
            } else {
                None
            },
            display,
            content,
            bcs,
        }),
        error: None,
    })
}

/// Helper function to serialize data to BCS and handle errors consistently
fn serialize_to_bcs<T: serde::Serialize>(
    data: &T,
    context: &str,
) -> Result<crate::common::BcsData, Status> {
    crate::common::BcsData::serialize_from(data)
        .map_err(|e| Status::internal(format!("{context} BCS serialization failed: {e}")))
}

/// Get display fields for an object
async fn get_display_fields(
    grpc_reader: &Arc<crate::types::GrpcReader>,
    original_object: &Object,
    original_layout: &Option<MoveStructLayout>,
) -> Result<DisplayFieldsResponse, Status> {
    // Check if we have access to both AuthorityState and TransactionKeyValueStore
    let (authority_state, kv_store) = match (
        grpc_reader.authority_state().as_ref(),
        grpc_reader.transaction_kv_store().as_ref(),
    ) {
        (Some(state), Some(kv_store)) => (state, kv_store),
        _ => {
            // Graceful fallback: return empty display fields if dependencies not available
            return Ok(DisplayFieldsResponse {
                data: None,
                error: None,
            });
        }
    };

    // Extract object type and layout, same logic as JSON RPC
    let Some((object_type, layout)) =
        iota_json_rpc::read_api::get_object_type_and_struct(original_object, original_layout)
            .map_err(|e| Status::internal(format!("Failed to get object type and struct: {e}")))?
    else {
        return Ok(DisplayFieldsResponse {
            data: None,
            error: None,
        });
    };

    // Query for display object, same as JSON RPC
    let mut events = authority_state
        .query_events(
            kv_store,
            EventFilter::MoveEventType(DisplayVersionUpdatedEvent::type_(&object_type)),
            None,
            1,
            true,
        )
        .await
        .map_err(|e| Status::internal(format!("Failed to query display events: {e}")))?;

    // Process display object if found
    if let Some(event) = events.pop() {
        let display: DisplayVersionUpdatedEvent = bcs::from_bytes(&event.bcs.into_bytes())
            .map_err(|e| Status::internal(format!("Failed to deserialize display event: {e}")))?;

        return iota_json_rpc::read_api::get_rendered_fields(display.fields, &layout)
            .map_err(|e| Status::internal(format!("Failed to render display fields: {e}")));
    }

    Ok(DisplayFieldsResponse {
        data: None,
        error: None,
    })
}
