// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::sync::Arc;

use futures::StreamExt;
use iota_json_rpc_types::{IotaTransactionBlockEffectsAPI, IotaTransactionKind, TransactionFilter};
use iota_types::base_types::{IotaAddress, ObjectID};
use tokio_util::sync::CancellationToken;
use tonic::{Request, Response, Status};
use tracing::debug;

use crate::{
    transactions::{
        Transaction, TransactionStreamRequest, transaction_service_server::TransactionService,
    },
    types::EventSubscriber,
};

pub struct TransactionGrpcService {
    pub event_subscriber: Arc<dyn EventSubscriber>,
    pub cancellation_token: CancellationToken,
}

impl TransactionGrpcService {
    pub fn new(
        event_subscriber: Arc<dyn EventSubscriber>,
        cancellation_token: CancellationToken,
    ) -> Self {
        Self {
            event_subscriber,
            cancellation_token,
        }
    }
}

// The `TransactionService` is the auto-generated trait from the protobuf
// definition. It's generated by tonic/protobuf and defines the interface that
// any gRPC transaction service must implement.
#[tonic::async_trait]
impl TransactionService for TransactionGrpcService {
    type StreamTransactionsStream =
        std::pin::Pin<Box<dyn futures::Stream<Item = Result<Transaction, Status>> + Send>>;

    async fn stream_transactions(
        &self,
        request: Request<TransactionStreamRequest>,
    ) -> Result<Response<Self::StreamTransactionsStream>, Status> {
        let proto_filter = request
            .into_inner()
            .filter
            .ok_or_else(|| Status::invalid_argument("Filter is required"))?;

        let transaction_filter = create_transaction_filter(&proto_filter)?;
        debug!("New gRPC client subscribed with filter: {transaction_filter:?}");

        // Subscribe to transactions using the EventSubscriber trait
        let transaction_stream = self
            .event_subscriber
            .subscribe_transactions(transaction_filter);
        let cancellation_token = self.cancellation_token.clone();

        let stream = async_stream::try_stream! {
            // Pin the stream for use with .next() and tokio::select!
            // Safe because the stream has Unpin bound
            let mut pinned_stream = std::pin::Pin::new(transaction_stream);

            loop {
                let transaction_result = tokio::select! {
                    transaction_option = pinned_stream.next() => transaction_option,
                    _ = cancellation_token.cancelled() => {
                        debug!("Transaction stream cancelled");
                        None
                    }
                };

                match transaction_result {
                    Some(transaction_effects) => {
                        debug!(
                            "Transaction matched filter: TX: {}",
                            transaction_effects.transaction_digest()
                        );

                        // Convert to protobuf Transaction
                        let proto_transaction = Transaction::from(&transaction_effects);

                        yield proto_transaction;
                    }
                    None => {
                        // Stream ended or cancellation occurred
                        debug!("Transaction stream ended");
                        break;
                    }
                }
            }
        };

        Ok(Response::new(Box::pin(stream)))
    }
}

/// Convert protobuf TransactionFilter to iota_json_rpc_types::TransactionFilter
fn create_transaction_filter(
    proto_filter: &crate::transactions::TransactionFilter,
) -> Result<TransactionFilter, Status> {
    use crate::transactions::transaction_filter::Filter;

    match &proto_filter.filter {
        Some(Filter::All(_)) => {
            // For "All" transactions, include all possible transaction kinds
            Ok(TransactionFilter::TransactionKindIn(vec![
                IotaTransactionKind::SystemTransaction,
                IotaTransactionKind::ProgrammableTransaction,
                IotaTransactionKind::Genesis,
                IotaTransactionKind::ConsensusCommitPrologueV1,
                IotaTransactionKind::AuthenticatorStateUpdateV1,
                IotaTransactionKind::RandomnessStateUpdate,
                IotaTransactionKind::EndOfEpochTransaction,
            ]))
        }
        Some(Filter::Checkpoint(f)) => Ok(TransactionFilter::Checkpoint(f.checkpoint)),
        Some(Filter::MoveFunction(f)) => {
            let package_id = parse_object_id(&f.package_id, "Package ID")?;
            Ok(TransactionFilter::MoveFunction {
                package: package_id,
                module: f.module.clone(),
                function: f.function.clone(),
            })
        }
        Some(Filter::InputObject(f)) => {
            let object_id = parse_object_id(&f.object_id, "Object ID")?;
            Ok(TransactionFilter::InputObject(object_id))
        }
        Some(Filter::ChangedObject(f)) => {
            let object_id = parse_object_id(&f.object_id, "Object ID")?;
            Ok(TransactionFilter::ChangedObject(object_id))
        }
        Some(Filter::FromAddress(f)) => {
            let address = parse_iota_address(&f.address, "From address")?;
            Ok(TransactionFilter::FromAddress(address))
        }
        Some(Filter::ToAddress(f)) => {
            let address = parse_iota_address(&f.address, "To address")?;
            Ok(TransactionFilter::ToAddress(address))
        }
        Some(Filter::FromAndToAddress(f)) => {
            let from_address = parse_iota_address(&f.from_address, "From address")?;
            let to_address = parse_iota_address(&f.to_address, "To address")?;
            Ok(TransactionFilter::FromAndToAddress {
                from: from_address,
                to: to_address,
            })
        }
        Some(Filter::FromOrToAddress(f)) => {
            let address = parse_iota_address(&f.address, "From or to address")?;
            Ok(TransactionFilter::FromOrToAddress { addr: address })
        }
        Some(Filter::TransactionKind(f)) => {
            let kind = match crate::transactions::TransactionKind::try_from(f.kind) {
                Ok(crate::transactions::TransactionKind::SystemTransaction) => {
                    IotaTransactionKind::SystemTransaction
                }
                Ok(crate::transactions::TransactionKind::ProgrammableTransaction) => {
                    IotaTransactionKind::ProgrammableTransaction
                }
                Ok(crate::transactions::TransactionKind::Genesis) => IotaTransactionKind::Genesis,
                Ok(crate::transactions::TransactionKind::ConsensusCommitPrologueV1) => {
                    IotaTransactionKind::ConsensusCommitPrologueV1
                }
                Ok(crate::transactions::TransactionKind::AuthenticatorStateUpdateV1) => {
                    IotaTransactionKind::AuthenticatorStateUpdateV1
                }
                Ok(crate::transactions::TransactionKind::RandomnessStateUpdate) => {
                    IotaTransactionKind::RandomnessStateUpdate
                }
                Ok(crate::transactions::TransactionKind::EndOfEpochTransaction) => {
                    IotaTransactionKind::EndOfEpochTransaction
                }
                Err(_) => return Err(Status::invalid_argument("Invalid transaction kind")),
            };
            Ok(TransactionFilter::TransactionKind(kind))
        }
        Some(Filter::TransactionKindIn(f)) => {
            let mut kinds = Vec::new();
            for k in &f.kinds {
                let kind = match crate::transactions::TransactionKind::try_from(*k) {
                    Ok(crate::transactions::TransactionKind::SystemTransaction) => {
                        IotaTransactionKind::SystemTransaction
                    }
                    Ok(crate::transactions::TransactionKind::ProgrammableTransaction) => {
                        IotaTransactionKind::ProgrammableTransaction
                    }
                    Ok(crate::transactions::TransactionKind::Genesis) => {
                        IotaTransactionKind::Genesis
                    }
                    Ok(crate::transactions::TransactionKind::ConsensusCommitPrologueV1) => {
                        IotaTransactionKind::ConsensusCommitPrologueV1
                    }
                    Ok(crate::transactions::TransactionKind::AuthenticatorStateUpdateV1) => {
                        IotaTransactionKind::AuthenticatorStateUpdateV1
                    }
                    Ok(crate::transactions::TransactionKind::RandomnessStateUpdate) => {
                        IotaTransactionKind::RandomnessStateUpdate
                    }
                    Ok(crate::transactions::TransactionKind::EndOfEpochTransaction) => {
                        IotaTransactionKind::EndOfEpochTransaction
                    }
                    Err(_) => {
                        return Err(Status::invalid_argument("Invalid transaction kind in list"));
                    }
                };
                kinds.push(kind);
            }
            Ok(TransactionFilter::TransactionKindIn(kinds))
        }
        None => {
            // Default to all transaction types
            Ok(TransactionFilter::TransactionKindIn(vec![
                IotaTransactionKind::SystemTransaction,
                IotaTransactionKind::ProgrammableTransaction,
                IotaTransactionKind::Genesis,
                IotaTransactionKind::ConsensusCommitPrologueV1,
                IotaTransactionKind::AuthenticatorStateUpdateV1,
                IotaTransactionKind::RandomnessStateUpdate,
                IotaTransactionKind::EndOfEpochTransaction,
            ]))
        }
    }
}

// Helper functions to reduce repetition and improve error messages
fn parse_object_id(
    address: &Option<crate::common::Address>,
    field_name: &str,
) -> Result<ObjectID, Status> {
    let address = address
        .as_ref()
        .ok_or_else(|| Status::invalid_argument(format!("{field_name} is required")))?;

    if address.address.len() != 32 {
        return Err(Status::invalid_argument(format!(
            "{field_name} must be 32 bytes, got {}",
            address.address.len()
        )));
    }

    let mut bytes = [0u8; 32];
    bytes.copy_from_slice(&address.address);
    ObjectID::from_bytes(bytes)
        .map_err(|e| Status::invalid_argument(format!("Invalid {field_name}: {e}")))
}

fn parse_iota_address(
    address: &Option<crate::common::Address>,
    field_name: &str,
) -> Result<IotaAddress, Status> {
    let address = address
        .as_ref()
        .ok_or_else(|| Status::invalid_argument(format!("{field_name} is required")))?;

    if address.address.len() != 32 {
        return Err(Status::invalid_argument(format!(
            "{field_name} must be 32 bytes, got {}",
            address.address.len()
        )));
    }

    let mut bytes = [0u8; 32];
    bytes.copy_from_slice(&address.address);
    IotaAddress::from_bytes(bytes)
        .map_err(|e| Status::invalid_argument(format!("Invalid {field_name}: {e}")))
}

// Versioned conversion from native IOTA types to gRPC protobuf
impl From<&iota_json_rpc_types::IotaTransactionBlockEffects> for Transaction {
    fn from(effects: &iota_json_rpc_types::IotaTransactionBlockEffects) -> Self {
        match effects {
            iota_json_rpc_types::IotaTransactionBlockEffects::V1(v1_effects) => Transaction {
                message_version: "v1".to_string(),
                effects: Some(crate::transactions::transaction::Effects::V1(
                    convert_v1_effects(v1_effects),
                )),
            }, /* Future versions can be added here:
                * IotaTransactionBlockEffects::V2(v2_effects) => { ... } */
        }
    }
}

// Convert V1 effects to proto format
fn convert_v1_effects(
    effects: &iota_json_rpc_types::IotaTransactionBlockEffectsV1,
) -> crate::transactions::TransactionEffectsV1 {
    crate::transactions::TransactionEffectsV1 {
        transaction_digest: Some(crate::common::Digest {
            digest: effects.transaction_digest.inner().to_vec(),
        }),
        status: Some(convert_execution_status(&effects.status)),
        executed_epoch: effects.executed_epoch,
        gas_used: Some(convert_gas_cost_summary(&effects.gas_used)),
        created: effects
            .created
            .iter()
            .map(convert_owned_object_ref)
            .collect(),
        mutated: effects
            .mutated
            .iter()
            .map(convert_owned_object_ref)
            .collect(),
        unwrapped: effects
            .unwrapped
            .iter()
            .map(convert_owned_object_ref)
            .collect(),
        deleted: effects.deleted.iter().map(convert_object_ref).collect(),
        unwrapped_then_deleted: effects
            .unwrapped_then_deleted
            .iter()
            .map(convert_object_ref)
            .collect(),
        wrapped: effects.wrapped.iter().map(convert_object_ref).collect(),
        gas_object: Some(convert_owned_object_ref(&effects.gas_object)),
        shared_objects: effects
            .shared_objects
            .iter()
            .map(convert_object_ref)
            .collect(),
        dependencies: effects
            .dependencies
            .iter()
            .map(|digest| crate::common::Digest {
                digest: digest.into_inner().to_vec(),
            })
            .collect(),
        modified_at_versions: effects
            .modified_at_versions()
            .iter()
            .map(
                |(object_id, sequence_number)| crate::transactions::ModifiedAtVersions {
                    object_id: Some(crate::common::Address {
                        address: object_id.into_bytes().to_vec(),
                    }),
                    sequence_number: sequence_number.value(),
                },
            )
            .collect(),
        events_digest: effects.events_digest.map(|digest| crate::common::Digest {
            digest: digest.into_inner().to_vec(),
        }),
    }
}

fn convert_execution_status(
    status: &iota_json_rpc_types::IotaExecutionStatus,
) -> crate::transactions::ExecutionStatus {
    let status_variant = match status {
        iota_json_rpc_types::IotaExecutionStatus::Success => {
            crate::transactions::execution_status::Status::Success(crate::transactions::Success {})
        }
        iota_json_rpc_types::IotaExecutionStatus::Failure { error } => {
            crate::transactions::execution_status::Status::Failure(crate::transactions::Failure {
                error: error.clone(),
            })
        }
    };
    crate::transactions::ExecutionStatus {
        status: Some(status_variant),
    }
}

fn convert_gas_cost_summary(
    gas: &iota_types::gas::GasCostSummary,
) -> crate::transactions::GasCostSummary {
    crate::transactions::GasCostSummary {
        computation_cost: gas.computation_cost,
        computation_cost_burned: gas.computation_cost_burned,
        storage_cost: gas.storage_cost,
        storage_rebate: gas.storage_rebate,
        non_refundable_storage_fee: gas.non_refundable_storage_fee,
    }
}

fn convert_owned_object_ref(
    obj_ref: &iota_json_rpc_types::OwnedObjectRef,
) -> crate::transactions::OwnedObjectRef {
    crate::transactions::OwnedObjectRef {
        reference: Some(convert_object_ref(&obj_ref.reference)),
        owner: Some(convert_owner(&obj_ref.owner)),
    }
}

fn convert_object_ref(obj_ref: &iota_json_rpc_types::IotaObjectRef) -> crate::common::ObjectRef {
    crate::common::ObjectRef {
        object_id: Some(crate::common::Address {
            address: obj_ref.object_id.into_bytes().to_vec(),
        }),
        version: obj_ref.version.value(),
        digest: Some(crate::common::Digest {
            digest: obj_ref.digest.into_inner().to_vec(),
        }),
    }
}

fn convert_owner(owner: &iota_types::object::Owner) -> crate::transactions::Owner {
    let owner_variant = match owner {
        iota_types::object::Owner::AddressOwner(addr) => {
            crate::transactions::owner::Owner::AddressOwner(crate::common::Address {
                address: addr.as_ref().to_vec(),
            })
        }
        iota_types::object::Owner::ObjectOwner(addr) => {
            crate::transactions::owner::Owner::ObjectOwner(crate::transactions::ObjectOwner {
                address: Some(crate::common::Address {
                    address: addr.as_ref().to_vec(),
                }),
            })
        }
        iota_types::object::Owner::Shared {
            initial_shared_version,
        } => crate::transactions::owner::Owner::Shared(crate::transactions::Shared {
            initial_shared_version: initial_shared_version.value(),
        }),
        iota_types::object::Owner::Immutable => {
            crate::transactions::owner::Owner::Immutable(crate::transactions::Immutable {})
        }
    };
    crate::transactions::Owner {
        owner: Some(owner_variant),
    }
}
