// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::sync::Arc;

use futures::StreamExt;
use iota_core::subscription_handler::SubscriptionHandler;
use iota_json_rpc_types::{IotaTransactionBlockEffectsAPI, IotaTransactionKind, TransactionFilter};
use iota_types::base_types::{IotaAddress, ObjectID};
use tokio_util::sync::CancellationToken;
use tonic::{Request, Response, Status};
use tracing::debug;

use crate::transactions::{
    Transaction, TransactionStreamRequest, transaction_service_server::TransactionService,
};

pub struct TransactionGrpcService {
    pub event_subscriber: Arc<SubscriptionHandler>,
    pub cancellation_token: CancellationToken,
}

impl TransactionGrpcService {
    pub fn new(
        event_subscriber: Arc<SubscriptionHandler>,
        cancellation_token: CancellationToken,
    ) -> Self {
        Self {
            event_subscriber,
            cancellation_token,
        }
    }
}

// The `TransactionService` is the auto-generated trait from the protobuf
// definition. It's generated by tonic/protobuf and defines the interface that
// any gRPC transaction service must implement.
#[tonic::async_trait]
impl TransactionService for TransactionGrpcService {
    type StreamTransactionsStream =
        std::pin::Pin<Box<dyn futures::Stream<Item = Result<Transaction, Status>> + Send>>;

    async fn stream_transactions(
        &self,
        request: Request<TransactionStreamRequest>,
    ) -> Result<Response<Self::StreamTransactionsStream>, Status> {
        let proto_filter = request
            .into_inner()
            .filter
            .ok_or_else(|| Status::invalid_argument("Filter is required"))?;

        let transaction_filter = create_transaction_filter(&proto_filter)?;
        debug!("New gRPC client subscribed with filter: {transaction_filter:?}");

        // Subscribe to transactions using the EventSubscriber trait
        let transaction_stream = self
            .event_subscriber
            .subscribe_transactions(transaction_filter);
        let cancellation_token = self.cancellation_token.clone();

        let stream = async_stream::try_stream! {
            // Pin the stream for use with .next() and tokio::select!
            // Safe because the stream has Unpin bound
            let mut pinned_stream = std::pin::Pin::new(transaction_stream);

            loop {
                let transaction_result = tokio::select! {
                    transaction_option = pinned_stream.next() => transaction_option,
                    _ = cancellation_token.cancelled() => {
                        debug!("Transaction stream cancelled");
                        None
                    }
                };

                match transaction_result {
                    Some(transaction_effects) => {
                        debug!(
                            "Transaction matched filter: TX: {}",
                            transaction_effects.transaction_digest()
                        );

                        // Convert to protobuf Transaction
                        let proto_transaction = Transaction::from(&transaction_effects);

                        yield proto_transaction;
                    }
                    None => {
                        // Stream ended or cancellation occurred
                        debug!("Transaction stream ended");
                        break;
                    }
                }
            }
        };

        Ok(Response::new(Box::pin(stream)))
    }
}

/// Convert protobuf TransactionFilter to iota_json_rpc_types::TransactionFilter
fn create_transaction_filter(
    proto_filter: &crate::transactions::TransactionFilter,
) -> Result<TransactionFilter, Status> {
    use crate::transactions::transaction_filter::Filter;

    match &proto_filter.filter {
        Some(Filter::All(_)) => {
            // For "All" transactions, include all possible transaction kinds
            Ok(TransactionFilter::TransactionKindIn(vec![
                IotaTransactionKind::SystemTransaction,
                IotaTransactionKind::ProgrammableTransaction,
                IotaTransactionKind::Genesis,
                IotaTransactionKind::ConsensusCommitPrologueV1,
                IotaTransactionKind::AuthenticatorStateUpdateV1,
                IotaTransactionKind::RandomnessStateUpdate,
                IotaTransactionKind::EndOfEpochTransaction,
            ]))
        }
        Some(Filter::Checkpoint(f)) => Ok(TransactionFilter::Checkpoint(f.checkpoint)),
        Some(Filter::MoveFunction(f)) => {
            let package_id = parse_object_id(&f.package_id, "Package ID")?;
            Ok(TransactionFilter::MoveFunction {
                package: package_id,
                module: f.module.clone(),
                function: f.function.clone(),
            })
        }
        Some(Filter::InputObject(f)) => {
            let object_id = parse_object_id(&f.object_id, "Object ID")?;
            Ok(TransactionFilter::InputObject(object_id))
        }
        Some(Filter::ChangedObject(f)) => {
            let object_id = parse_object_id(&f.object_id, "Object ID")?;
            Ok(TransactionFilter::ChangedObject(object_id))
        }
        Some(Filter::FromAddress(f)) => {
            let address = parse_iota_address(&f.address, "From address")?;
            Ok(TransactionFilter::FromAddress(address))
        }
        Some(Filter::ToAddress(f)) => {
            let address = parse_iota_address(&f.address, "To address")?;
            Ok(TransactionFilter::ToAddress(address))
        }
        Some(Filter::FromAndToAddress(f)) => {
            let from_address = parse_iota_address(&f.from_address, "From address")?;
            let to_address = parse_iota_address(&f.to_address, "To address")?;
            Ok(TransactionFilter::FromAndToAddress {
                from: from_address,
                to: to_address,
            })
        }
        Some(Filter::FromOrToAddress(f)) => {
            let address = parse_iota_address(&f.address, "From or to address")?;
            Ok(TransactionFilter::FromOrToAddress { addr: address })
        }
        Some(Filter::TransactionKind(f)) => {
            let kind = match crate::transactions::TransactionKind::try_from(f.kind) {
                Ok(crate::transactions::TransactionKind::SystemTransaction) => {
                    IotaTransactionKind::SystemTransaction
                }
                Ok(crate::transactions::TransactionKind::ProgrammableTransaction) => {
                    IotaTransactionKind::ProgrammableTransaction
                }
                Ok(crate::transactions::TransactionKind::Genesis) => IotaTransactionKind::Genesis,
                Ok(crate::transactions::TransactionKind::ConsensusCommitPrologueV1) => {
                    IotaTransactionKind::ConsensusCommitPrologueV1
                }
                Ok(crate::transactions::TransactionKind::AuthenticatorStateUpdateV1) => {
                    IotaTransactionKind::AuthenticatorStateUpdateV1
                }
                Ok(crate::transactions::TransactionKind::RandomnessStateUpdate) => {
                    IotaTransactionKind::RandomnessStateUpdate
                }
                Ok(crate::transactions::TransactionKind::EndOfEpochTransaction) => {
                    IotaTransactionKind::EndOfEpochTransaction
                }
                Err(_) => return Err(Status::invalid_argument("Invalid transaction kind")),
            };
            Ok(TransactionFilter::TransactionKind(kind))
        }
        Some(Filter::TransactionKindIn(f)) => {
            let mut kinds = Vec::new();
            for k in &f.kinds {
                let kind = match crate::transactions::TransactionKind::try_from(*k) {
                    Ok(crate::transactions::TransactionKind::SystemTransaction) => {
                        IotaTransactionKind::SystemTransaction
                    }
                    Ok(crate::transactions::TransactionKind::ProgrammableTransaction) => {
                        IotaTransactionKind::ProgrammableTransaction
                    }
                    Ok(crate::transactions::TransactionKind::Genesis) => {
                        IotaTransactionKind::Genesis
                    }
                    Ok(crate::transactions::TransactionKind::ConsensusCommitPrologueV1) => {
                        IotaTransactionKind::ConsensusCommitPrologueV1
                    }
                    Ok(crate::transactions::TransactionKind::AuthenticatorStateUpdateV1) => {
                        IotaTransactionKind::AuthenticatorStateUpdateV1
                    }
                    Ok(crate::transactions::TransactionKind::RandomnessStateUpdate) => {
                        IotaTransactionKind::RandomnessStateUpdate
                    }
                    Ok(crate::transactions::TransactionKind::EndOfEpochTransaction) => {
                        IotaTransactionKind::EndOfEpochTransaction
                    }
                    Err(_) => {
                        return Err(Status::invalid_argument("Invalid transaction kind in list"));
                    }
                };
                kinds.push(kind);
            }
            Ok(TransactionFilter::TransactionKindIn(kinds))
        }
        None => {
            // Default to all transaction types
            Ok(TransactionFilter::TransactionKindIn(vec![
                IotaTransactionKind::SystemTransaction,
                IotaTransactionKind::ProgrammableTransaction,
                IotaTransactionKind::Genesis,
                IotaTransactionKind::ConsensusCommitPrologueV1,
                IotaTransactionKind::AuthenticatorStateUpdateV1,
                IotaTransactionKind::RandomnessStateUpdate,
                IotaTransactionKind::EndOfEpochTransaction,
            ]))
        }
    }
}

// Helper functions to reduce repetition and improve error messages
fn parse_object_id(
    address: &Option<crate::common::Address>,
    field_name: &str,
) -> Result<ObjectID, Status> {
    let address = address
        .as_ref()
        .ok_or_else(|| Status::invalid_argument(format!("{field_name} is required")))?;

    if address.address.len() != 32 {
        return Err(Status::invalid_argument(format!(
            "{field_name} must be 32 bytes, got {}",
            address.address.len()
        )));
    }

    let mut bytes = [0u8; 32];
    bytes.copy_from_slice(&address.address);
    ObjectID::from_bytes(bytes)
        .map_err(|e| Status::invalid_argument(format!("Invalid {field_name}: {e}")))
}

fn parse_iota_address(
    address: &Option<crate::common::Address>,
    field_name: &str,
) -> Result<IotaAddress, Status> {
    let address = address
        .as_ref()
        .ok_or_else(|| Status::invalid_argument(format!("{field_name} is required")))?;

    if address.address.len() != 32 {
        return Err(Status::invalid_argument(format!(
            "{field_name} must be 32 bytes, got {}",
            address.address.len()
        )));
    }

    let mut bytes = [0u8; 32];
    bytes.copy_from_slice(&address.address);
    IotaAddress::from_bytes(bytes)
        .map_err(|e| Status::invalid_argument(format!("Invalid {field_name}: {e}")))
}

// Conversion from JSON-RPC types to gRPC protobuf using JSON serialization
impl From<&iota_json_rpc_types::IotaTransactionBlockEffects> for Transaction {
    fn from(effects: &iota_json_rpc_types::IotaTransactionBlockEffects) -> Self {
        // Serialize JSON-RPC effects directly to JSON (much simpler than BCS)
        let json_data = serde_json::to_vec(effects)
            .expect("IotaTransactionBlockEffects should always serialize to JSON");

        Transaction { json_data }
    }
}
